import { useEffect, useMemo, useState } from 'react';
import DailyCoaching from '../components/dashboard/DailyCoaching';
import QuickActions from '../components/dashboard/QuickActions';
import TodayTasks from '../components/dashboard/TodayTasks';
import WeeklyOverview from '../components/dashboard/WeeklyOverview';
import CalendarPanel from '../components/dashboard/CalendarPanel';
import { api } from '../lib/api';
import { usePomodoro } from '../hooks/usePomodoro';
import { useAppStore } from '../store/useAppStore';
import type {
  MoodState,
  PetType,
  ReviewTask,
  StudentTaskType,
  TaskVector,
} from '../types';
import { DEFAULT_POMODORO_MAP, STUDENT_TASK_OPTIONS } from '../lib/constants';
import { toISODate } from '../lib/format';

const MOOD_KEY = 'ai-learning-wellness';
const PET_KEY = 'ai-learning-pet';

const getStoredMood = (): MoodState => {
  if (typeof window === 'undefined') {
    return { mood: 3, focus: 3 };
  }
  const raw = window.localStorage.getItem(MOOD_KEY);
  if (!raw) return { mood: 3, focus: 3 };
  try {
    const parsed = JSON.parse(raw) as MoodState;
    return { mood: parsed.mood ?? 3, focus: parsed.focus ?? 3 };
  } catch {
    return { mood: 3, focus: 3 };
  }
};

const getStoredPet = (): PetType => {
  if (typeof window === 'undefined') {
    return 'cat';
  }
  const raw = window.localStorage.getItem(PET_KEY);
  if (!raw) return 'cat';
  return raw as PetType;
};

const SMART_OFFSETS = [0, 3, 7, 14];

const getDefaultMethod = (type: StudentTaskType) =>
  STUDENT_TASK_OPTIONS.find((option) => option.value === type)?.defaultMethod ?? null;

const generateId = () =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random()}`;

const buildSmartSchedule = (input: {
  title: string;
  type: StudentTaskType;
  dueDate: string;
  vector: TaskVector;
}): ReviewTask[] => {
  const baseDate = new Date(input.dueDate);
  const validBase = Number.isNaN(baseDate.getTime()) ? new Date() : baseDate;
  const method = getDefaultMethod(input.type);
  const pomodoros = DEFAULT_POMODORO_MAP[input.type] ?? 2;
  const baseId = generateId();

  if (method === 'spaced-review') {
    return SMART_OFFSETS.map((offset, index) => {
      const scheduled = new Date(validBase);
      scheduled.setDate(validBase.getDate() + offset);
      const iso = toISODate(scheduled);
      const labelPrefix = offset === 0 ? '' : `D+${offset} 複習：`;
      const title = `${labelPrefix}${input.title}｜番茄 ${pomodoros} 顆`;
      return {
        id: index === 0 ? baseId : generateId(),
        title,
        dueDate: iso,
        status: 'pending' as const,
        type: input.type,
        method,
        autoGenerated: offset !== 0,
        relatedTaskId: baseId,
        vector: input.vector,
      };
    });
  }

  const title =
    method === 'active-recall' ? `${input.title}｜番茄 ${pomodoros} 顆` : input.title;

  return [
    {
      id: baseId,
      title,
      dueDate: toISODate(validBase),
      status: 'pending',
      type: input.type,
      method,
      autoGenerated: false,
      relatedTaskId: baseId,
      vector: input.vector,
    },
  ];
};

const Dashboard = () => {
  const [tasks, setTasks] = useState<ReviewTask[]>([]);

  const [weeklyStats, setWeeklyStats] = useState({ completed: 0, pending: 0 });
  const [mood, setMood] = useState<MoodState>(() => getStoredMood());
  const pomodoro = usePomodoro();
  const selectedPet = useAppStore((state) => state.selectedPet);
  const setSelectedPet = useAppStore((state) => state.setSelectedPet);
  const studyPlan = useAppStore((state) => state.studyPlan);

  const handleAddTask = (input: {
    title: string;
    type: StudentTaskType;
    dueDate: string;
    vector: TaskVector;
  }) => {
    const smartTasks = buildSmartSchedule(input);
    setTasks((prev) =>
      [...prev, ...smartTasks].sort((a, b) => a.dueDate.localeCompare(b.dueDate)),
    );
  };

  const handleDeleteTask = (id: string) => {
    setTasks((prev) => {
      const target = prev.find((task) => task.id === id);
      if (!target) return prev;
      const groupId = target.autoGenerated ? target.relatedTaskId ?? target.id : target.id;
      return prev.filter(
        (task) => task.id !== groupId && task.relatedTaskId !== groupId && task.id !== id,
      );
    });
  };

  useEffect(() => {
    api.getDashboard().then((data) => {
      setTasks(data.todayTasks);

      setWeeklyStats(data.weeklyStats);
    });
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(MOOD_KEY, JSON.stringify(mood));
    }
  }, [mood]);

  useEffect(() => {
    const stored = getStoredPet();
    setSelectedPet(stored);
  }, [setSelectedPet]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(PET_KEY, selectedPet);
    }
  }, [selectedPet]);

  const calendarEvents = useMemo(
    () => [
      ...tasks.map((task) => ({
        id: task.id,
        date: task.dueDate,
        title: task.title,
        type: 'task' as const,
        status: task.status,
        taskType: task.type,
      })),
      ...studyPlan.map((item) => ({
        id: item.id,
        date: item.dueDate,
        title: `[複習] ${item.course} - ${item.topic}`,
        type: 'study-plan' as const,
      })),
    ],
    [tasks, studyPlan],
  );

  return (
    <div className="space-y-6">

      <div className="grid gap-6 lg:grid-cols-[1.2fr,0.8fr]">
        <TodayTasks tasks={tasks} onAddTask={handleAddTask} onDeleteTask={handleDeleteTask} />
        <DailyCoaching
          pomodoro={pomodoro}
          mood={mood}
          onMoodChange={setMood}
          selectedPet={selectedPet}
          onSelectPet={setSelectedPet}
        />
      </div>
      <QuickActions />


      {/* Weekly Progress */}
      <WeeklyOverview completed={weeklyStats.completed} pending={weeklyStats.pending} />

      <CalendarPanel
        events={calendarEvents}
        pomodoroHistory={pomodoro.history}
        todayCount={pomodoro.completedToday}
        currentDate={pomodoro.currentDate}
      />
    </div>
  );
};

export default Dashboard;
