import { useEffect, useMemo, useState } from 'react';
import DailyCoaching from '../components/dashboard/DailyCoaching';
import TodayTasks from '../components/dashboard/TodayTasks';
import WeeklyOverview from '../components/dashboard/WeeklyOverview';
import CalendarPanel from '../components/dashboard/CalendarPanel';
import { api } from '../lib/api';
import { usePomodoro } from '../hooks/usePomodoro';
import { useAppStore } from '../store/useAppStore';
import type {
  PetType,
  ReviewTask,
  StudentTaskType,
  TaskVector,
} from '../types';
import { DEFAULT_POMODORO_MAP, STUDENT_TASK_OPTIONS } from '../lib/constants';
import { toISODate } from '../lib/format';

const PET_KEY = 'ai-learning-pet';

const getStoredPet = (): PetType => {
  if (typeof window === 'undefined') {
    return 'cat';
  }
  const raw = window.localStorage.getItem(PET_KEY);
  if (!raw) return 'cat';
  return raw as PetType;
};

const SMART_OFFSETS = [0, 3, 7, 14];

const getDefaultMethod = (type: StudentTaskType) =>
  STUDENT_TASK_OPTIONS.find((option) => option.value === type)?.defaultMethod ?? null;

const generateId = () =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random()}`;

const buildSmartSchedule = (input: {
  title: string;
  type: StudentTaskType;
  dueDate: string;
  vector: TaskVector;
}): ReviewTask[] => {
  const baseDate = new Date(input.dueDate);
  const validBase = Number.isNaN(baseDate.getTime()) ? new Date() : baseDate;
  const method = getDefaultMethod(input.type);
  const pomodoros = DEFAULT_POMODORO_MAP[input.type] ?? 2;
  const baseId = generateId();

  if (method === 'spaced-review') {
    return SMART_OFFSETS.map((offset, index) => {
      const scheduled = new Date(validBase);
      scheduled.setDate(validBase.getDate() + offset);
      const iso = toISODate(scheduled);
      const labelPrefix = offset === 0 ? '' : `D+${offset} 複習：`;
      const title = `${labelPrefix}${input.title}｜番茄 ${pomodoros} 顆`;
      return {
        id: index === 0 ? baseId : generateId(),
        title,
        dueDate: iso,
        status: 'pending' as const,
        type: input.type,
        method,
        autoGenerated: offset !== 0,
        relatedTaskId: baseId,
        vector: input.vector,
      };
    });
  }

  const title =
    method === 'active-recall' ? `${input.title}｜番茄 ${pomodoros} 顆` : input.title;

  return [
    {
      id: baseId,
      title,
      dueDate: toISODate(validBase),
      status: 'pending',
      type: input.type,
      method,
      autoGenerated: false,
      relatedTaskId: baseId,
      vector: input.vector,
    },
  ];
};

import { useMemoryStore } from '../store/useMemoryStore';
import DailyProgress from '../components/dashboard/DailyProgress';
import MissionCard from '../components/dashboard/MissionCard';
import LearningAnalytics from '../components/dashboard/LearningAnalytics';


const Dashboard = () => {
  const [tasks, setTasks] = useState<ReviewTask[]>([]);
  const [weeklyStats, setWeeklyStats] = useState({ completed: 0, pending: 0 });
  const [activeTab, setActiveTab] = useState<'daily' | 'analytics'>('daily');

  const pomodoro = usePomodoro();
  const selectedPet = useAppStore((state) => state.selectedPet);
  const setSelectedPet = useAppStore((state) => state.setSelectedPet);
  const studyPlan = useAppStore((state) => state.studyPlan);

  const { dailyMissions, checkDailyReset } = useMemoryStore();

  useEffect(() => {
    checkDailyReset();
  }, [checkDailyReset]);

  const handleAddTask = (input: {
    title: string;
    type: StudentTaskType;
    dueDate: string;
    vector: TaskVector;
  }) => {
    const smartTasks = buildSmartSchedule(input);
    setTasks((prev) =>
      [...prev, ...smartTasks].sort((a, b) => a.dueDate.localeCompare(b.dueDate)),
    );
  };

  const handleDeleteTask = (id: string) => {
    setTasks((prev) => {
      const target = prev.find((task) => task.id === id);
      if (!target) return prev;
      const groupId = target.autoGenerated ? target.relatedTaskId ?? target.id : target.id;
      return prev.filter(
        (task) => task.id !== groupId && task.relatedTaskId !== groupId && task.id !== id,
      );
    });
  };

  const handleToggleTask = (id: string) => {
    setTasks((prev) =>
      prev.map((task) => {
        if (task.id === id) {
          const newStatus = task.status === 'done' ? 'pending' : 'done';

          // Trigger pet reward if completing task
          if (newStatus === 'done') {
            useAppStore.getState().rewardPet(10, 5); // 10 XP, -5 Hunger
            useAppStore.getState().triggerPet();
          }

          return { ...task, status: newStatus };
        }
        return task;
      })
    );
  };

  useEffect(() => {
    api.getDashboard().then((data) => {
      setTasks(data.todayTasks);
      setWeeklyStats(data.weeklyStats);
    });
  }, []);



  useEffect(() => {
    const stored = getStoredPet();
    setSelectedPet(stored);
  }, [setSelectedPet]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(PET_KEY, selectedPet);
    }
  }, [selectedPet]);

  const calendarEvents = useMemo(
    () => [
      ...tasks.map((task) => ({
        id: task.id,
        date: task.dueDate,
        title: task.title,
        type: 'task' as const,
        status: task.status,
        taskType: task.type,
      })),
      ...studyPlan.map((item) => ({
        id: item.id,
        date: item.dueDate,
        title: `[複習] ${item.course} - ${item.topic}`,
        type: 'study-plan' as const,
      })),
    ],
    [tasks, studyPlan],
  );

  return (
    <div className="space-y-6">
      {/* Header & Tabs */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">探險基地</h1>
        <div className="flex bg-gray-100 p-1 rounded-xl">
          <button
            onClick={() => setActiveTab('daily')}
            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'daily' ? 'bg-white shadow-sm text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
          >
            Daily View
          </button>
          <button
            onClick={() => setActiveTab('analytics')}
            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'analytics' ? 'bg-white shadow-sm text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
          >
            Analytics
          </button>
        </div>
      </div>

      {activeTab === 'daily' ? (
        <>
          {/* 0. Daily Progress & AI Goals */}
          <div className="mb-6">
            <DailyProgress />
          </div>

          {/* 1. Daily Missions (Top Priority) */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {dailyMissions.map(mission => (
              <MissionCard key={mission.id} mission={mission} />
            ))}
          </div>

          {/* 2. Today Tasks & Coaching */}
          <div className="grid gap-6 lg:grid-cols-[1.2fr,0.8fr]">
            <TodayTasks
              tasks={tasks}
              onAddTask={handleAddTask}
              onDeleteTask={handleDeleteTask}
              onToggleTask={handleToggleTask}
            />

            <div className="space-y-6">
              {/* Simplified Coaching / Encouragement */}
              <DailyCoaching
                pomodoro={pomodoro}
              />

              {/* Weekly Progress moved here */}
              <WeeklyOverview completed={weeklyStats.completed} pending={weeklyStats.pending} />
            </div>
          </div>

          {/* 3. Calendar */}
          <CalendarPanel
            events={calendarEvents}
            pomodoroHistory={pomodoro.history}
            todayCount={pomodoro.completedToday}
            currentDate={pomodoro.currentDate}
          />
        </>
      ) : (
        <LearningAnalytics />
      )}
    </div>
  );
};

export default Dashboard;
